@host = http://localhost:3000

### get all products
GET {{host}}/api/product/

### create product
POST {{host}}/api/product/
Content-Type: application/json

{
    "productName": "Incredible Frozen Gloves",
    "price": "244.00",
    "image": "https://loremflickr.com/640/480/abstract",
    "productDescription": "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
    "department": "Toys",
    "id": "5"
}

### login user
POST {{host}}/api/product/login/
Content-Type: application/json

{
  "email": "new1@gmail.com",
  "password": "new1"
}

### get curr user
POST {{host}}/api/me
Content-Type: application/json

{
  "id": "66cafd5aa0cb5be40db3338b"
}


### get curr user
DELETE {{host}}/api/test
Content-Type: application/json